### ISSUE TITLE
FAILED TO PARSE: Help

### ISSUE THREAD

**Issue by NealSavant** [mpcen/newworld-coordinate-tracker#7]
What reasons would this not be able to parse my location?

I enabled script calls from powershell using suggestions here:
https://www.partitionwizard.com/clone-disk/running-scripts-is-disabled-on-this-system.html

But still getting failed to parse error with characters following

**Comment by NealSavant** [comment]
I run this game on ultra wide, wondering if you or i can help build a config for other resolutions

**Comment by NaNraptor** [comment]
At the moment if you are on elvation at 1000 or above  OR  100 and below the code will always fail to get the correct location, this will be resolved soon I hope, the issue that tracks this problem is #4

**Comment by mpcen** [comment]
@NaNraptor i commented on the PR with some issues i ran into. In the meantime, I merged #9
